### ISSUE TITLE
BidEscrow Tracking Issue.

### ISSUE THREAD

**Issue by zie1ony** [make-software/dao-contracts#93]
List of features requested by the DEVxDAO members, that when implemented, should produce a bid escrow process with expected features.

- [ ] Reputation Token 
    - [ ] Move REP distribution logic into the Reputation Contract.
    - [ ] Allow CSPR distribution to all VAs, and take all REP under consideration.
    - [ ] Rewrite tests.
    - [ ] Burn REP dust.
    - [ ] Voters to use new token.
    - [ ] Bring back staking.

- [ ] Bid Escrow
    - [ ] Update BidEscrow to stake CSPR for an external worker.  
    - [ ] Implement bidding in BidEscrow.
        - [ ] Bidding process.
        - [ ] Bidding stakes management.
        - [ ] Rewrite job acceptation process.
        - [ ] Rewrite job cancelation process.
    - [ ] Remove minimum stake from Bidding
    - [ ] Automatic REP slash in case of not completing the job.
    - [ ] Implement the configurable governance payment (tax).
    - [ ] Internal worker participate in voting.

- [ ] Onbarding Voter should allow to stake CSPR and post proof by external worker.

# Full Bid Escrow Process
- Bidding process
    - Job poster posts a job
        - Job poster sends CSPR?
    - Workers posts bids.
    - Check if condions are met
    - Fail the process if needed.
    - Pick a bid.
        - Accept CSPR for nonVA worker.
    - New job is created.
        - Stakes are returned to non-picked workers.
        - Mint new REP (based on CSPR*ratio amount) to nonVA worker and use it as a stake on the job.
        - Add workers CSPR to the job poster reward.

- Job handling
    - Waiting for worker or job poster to submit a result. Job poster can submit a result if time has passed.
    - If voiting failed:
        - For VA worker - slash REP
        - For nonVA worker
            - Loses CSPR stake.
            - Redistribute staked worker's CSPR to all VAs or just those who particiated in voting.
        - For job poster - gets her CSPR back.
        - Redistribute REP to voting winners.
    - If no quorum (formal and informal) or informal voiting failes
        - Everything is returned.
        - For nonVA worker - REP tokens are burned.
    - If voting succeded:
        - Mint new REP (job_price * conversion_rate) to additional pool.
        - For nonVA that doesn't want to become VA:
            - Move prevously minted REP for the worker to additional poll.
            - Additional pool is redistributed among VA voter.
            - CSPR * governance_payment_ratio is transfered to multisig wallet.  
            - rest of CSPR * policing_rate is transfered to all VAs.
            - rest of the rest is given to worker.

        - If nonVA worker wants to become VA:
            - Mint VA Token for the worker.
            - Rest is like the VA worker flow.

        - If VA worker
            - Reputation is redistributed to winners.
            - CSPR * governance_payment_ratio is transfered to multisig wallet.  
            - Rest of CSPR is transfered to all VAs.
