### ISSUE TITLE
`final` version tracking issue.

### ISSUE THREAD

**Issue by zie1ony** [make-software/dao-contracts#97]
## Interface stabilization phase:
- [x] Refactor voting interface.
- [ ] Complete bid escrow algorith. 
- [ ] Special Onboarding.
- [ ] All variables and Gherkin tests.
- [ ] Slashing 100%.
- [ ] DOS Fee based on Dolars.
- [ ] Add all Events.
- [ ] Move token ids increments into token contracts.
- [ ] Centralize voting id generations.

## Refactor phase:
- [ ] Refactor DAOWorld.
- [ ] Refactor Bid Escrow and Governance Voting.
- [ ] Add simple profiler.
- [ ] Move Repository out of dao-modules.
- [ ] Fix number conversions.
- [ ] Tests for all contracts in Gherkin.
- [ ] Refactor Reputation.
- [ ] Bid Escrow Bidding tests.

This
